version: '3'

services: 
  apache:
    build: ./apache
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment: 
      - MYSQL_PASSWD=root
      - DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWD=lamp_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d       

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - host_php=mysql
    depends_on: 
      - mysql 

volumes:
  mysql_data: